services:
  super-app:
    build: .
    ports:
      - '5000:3000'
    volumes:
      - .:/auth-project
      - /auth-project/node_modules
    command: pnpm run dev
    environment:
      - MONGO_URI=mongodb://localhost:27017/swagger
    env_file:
      - .env
    depends_on:
      - mongo-db
    restart: always

  mongo-db:
    image: mongo:latest
    ports:
      - '27019:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
